### PR TITLE
Lodash v4 Compatibility

### PR DESCRIPTION
**Pull request by joshlasdin**
Removed usage of `_.object` and `_.invoke` in order to play nice with Lodash v4

### CODE REVIEW

**Comment by jmeas** [comment]
Thanks for the PR, @joshlasdin ! Can you remove the changes to the `dist` directory? I'll build them in the release commit ✌️

**Comment by joshlasdin** [comment]
No problem, updated without the `dist` build :+1:

**Comment by jmeas** [comment]
Nice @joshlasdin . I'll release this once I get to work in about an hour. Sorry for the slower turnaround

**Comment by joshlasdin** [comment]
@jmeas No worries! Thanks! 😄

**Comment by jamesplease** [comment]
Published as 1.3.2. Let me know if there are any issues :) And thanks again for the PR!

**Pull request merged**
