### PR TITLE
Update valid BB version

### PR DESCRIPTION
**Pull request by MeoMix**
1.3.3 came out and I don't think there's anything breaking from a quick glance at the changelog.

### CODE REVIEW

**Comment by jmeas** [comment]
Thanks! will release in a min

**Comment by jmeas** [comment]
p.s. gotta remember to update `bower.json`, too! I can do it this time :wink:

**Comment by MeoMix** [comment]
Pffft, Bower. Who still uses that :p Sorry.

**Comment by jmeas** [comment]
> Pffft, Bower. Who still uses that :p

lolol. I wish fewer people did 😦 

> Sorry.

no problem at all ;p

**Pull request merged**
